Repository thoth-station/cli-examples, pull requests merged in 2020-04, with the labels that each got.

#1 Add example with tf stack
  .github/CODEOWNERS
  .thoth.yaml
  Pipfile
  Pipfile.lock
  README.md
  app.py
  requirements.txt
  template/__init__.py
  template/version.py
Labels: approved, size/XL

#2 README is in reStructuredText
  README.rst
Labels: approved, size/XS

#5 Link to s2i-examples
  README.rst
Labels: approved, do-not-merge/needs-rebase, size/XS
