Repository thoth-station/cli-examples, pull requests merged in 2021-12, with the labels that each got.

#20 Update pyproject.toml to use Python 3.8
  pyproject.toml
Labels: size/XS

#14 Use Python 3.8 instead of Python 3.6
  .thoth.yaml
Labels: approved, size/XS, lgtm

#23 Add example application to demonstrate thamos resolution process
  Pipfile
  README.rst
  app.py
  game_of_life.py
Labels: approved, size/L

#27 Add configuration for CI
  .aicoe-ci.yaml
  .github/PULL_REQUEST_TEMPLATE.md
  .pre-commit-config.yaml
  .prow.yaml
  README.rst
  game_of_life.py
Labels: approved, size/M

#25 Add Pipfile with requirements
  Pipfile
  Pipfile.lock
Labels: approved, size/L

#29 Introduce play mode
  Pipfile
  Pipfile.lock
  game_of_life.py
Labels: approved, size/S

#31 Let snake play the game \o/
  game_of_life.py
Labels: approved, size/XS

#30 Simplify installation instructions
  README.rst
Labels: approved, size/M

#26 Use latest recommendation type by default
  .thoth.yaml
Labels: approved, size/XS

#24 Add .thoth_last_analysis_id to .gitignore
  .gitignore
Labels: approved, size/XS

#32 Add pillow as a vulnerability
  README.rst
  game_of_life.py
Labels: approved, size/S

#33 Minor README fixes
  README.rst
Labels: approved, size/XS

#35 Remove .zuul.yaml
  .zuul.yaml
Labels: approved, size/S

#36 Remove unused .coafile
  .coafile
Labels: approved, size/S

#34 Add missing direct dependency Pillow
  Pipfile
  Pipfile.lock
Labels: approved, size/L
